### PR TITLE
Add null checks

### PR DESCRIPTION
**Pull request by p455w0rd**
Fixes SonarSonic/Flux-Networks#68 & #28

### CODE REVIEW

**Comment by AEnterprise** [comment]
the 'better' aproach would be asking the tile if it has has the capability before requesting, it's a glorified null check but it what the hasCapability function was designed for

**Comment by p455w0rd** [comment]
true..will fix

**Comment by SonarSonic** [comment]
I'm fixing this another way

**Comment by AEnterprise** [comment]
@SonarSonic this is the way to fix this, you are currently asking for capabilities without any check if they are present at all

**Comment by p455w0rd** [comment]
way to be a dick :)

**Comment by SonarSonic** [comment]
@AEnterprise I check them in another class. The method which retrieves the handler checks the hasCapability stuff and any other things needed for the handler not to crash. Preventing it being checked more than necessary.

**Comment by AEnterprise** [comment]
that's another way to do it, wasn't obvious from your code

**Comment by p455w0rd** [comment]
my apologies

**Pull request closed without merging**
